# SwifterLog document generator jazzy settings

copyright: Copyright 2016-2019 rien@balancingrock.nl
author: Balancingrock
module: Http
documentation: docs/*.md
hide_documentation_coverage: false
xcodebuild_arguments: [-target, Http]
github_url: https://github.com/Balancingrock/Http
output: ~/Documents/Websites/swiftfire.nl/projects/http/reference
clean: true
theme: fullwidth
readme: README.md
documentation: docs/*.md
