# SwifterLog document generator jazzy settings

copyright: Copyright 2016-2017 Rien van der Lugt
author: Rien van der Lugt
module: Http
hide_documentation_coverage: true
xcodebuild_arguments: [-target, Http]
github_url: https://github.com/Balancingrock/Http
output: ~/Documents/Websites/sf/projects/http/reference
clean: true
theme: fullwidth
readme: README.md
documentation: docs/*.md
